name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-linux:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Setup Target
      run: |
          rustup target add x86_64-unknown-linux-musl
    - name: Build
      run: cargo build --target x86_64-unknown-linux-musl --release --verbose
    - name: Run Tests
      run: cargo test --target x86_64-unknown-linux-musl --verbose
    - name: Pre-release (linux)
      run: |
          cd target/x86_64-unknown-linux-musl/release
          zip -r kvs-x86_64-unknown-linux-musl.zip kvs
    - name: Upload Artifact
      uses: actions/upload-artifact@v3.0.0
      with:
        name: kvs-x86_64-unknown-linux-musl
        path: target/x86_64-unknown-linux-musl/release/kvs-x86_64-unknown-linux-musl.zip
  build-mac:
    runs-on: macOS-12
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --release --verbose
    - name: Run Tests
      run: cargo test --verbose
    - name: Pre-release (macOS)
      run: |
          cd target/release
          zip -r kvs-x86_64-apple-darwin.zip kvs
    - name: Upload Artifact
      uses: actions/upload-artifact@v3.0.0
      with:
        name: kvs-x86_64-apple-darwin
        path: target/release/kvs-x86_64-apple-darwin.zip
  release:
    needs: [build-linux, build-mac]
    runs-on: ubuntu-latest
    steps:
      - name: Download a Build Artifact
        uses: actions/download-artifact@v3.0.0
        with:
          path: artifacts
      - name: Upload artifacts & release assets
        uses: nanoufo/action-upload-artifacts-and-release-assets@v1.4
        with:
          path: artifacts
      - name: Automatic Releases
      # You may pin to the exact commit or the version.
      # uses: marvinpinto/action-automatic-releases@919008cf3f741b179569b7a6fb4d8860689ab7f0
        uses: marvinpinto/action-automatic-releases@v1.2.1
        with:
          # GitHub secret token
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: false
          title: "latest"
          # Assets to upload to the release
          files: artifacts
